name: CD Workflow

on:
  workflow_run:
    workflows:
      - CI Workflow
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure VM Py
        env:
          SSH_PASSWORD: ${{ secrets.PASSWORD }}
          SSH_HOST: ${{ secrets.HOST }}
          SSH_USER: ${{ secrets.USERNAME }}
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y sshpass

          sshpass -p "$SSH_PASSWORD" ssh \
            -o StrictHostKeyChecking=no \
            -o PreferredAuthentications=password \
            -o PubkeyAuthentication=no \
            "$SSH_USER@$SSH_HOST" << 'EOF'
              cd ~/weather-app
              git pull origin main
              source venv/bin/activate
              pip install -r requirements.txt
              pkill -f "python app.py" || true
              nohup python app.py > app.log 2>&1 &
          EOF
